name: Create Release from main
on:
  push:
    branches:
      - agustin/hotfix/gh-action-release

jobs:
  release-main:
    runs-on: ubuntu-latest
    permissions: # As per https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
      contents: write

    steps:
      - uses: actions/checkout@v4
      # Depends on the following format from the commit message:
      # Release vX.Y.Z ...
      #
      # Release notes here
      # ...
      - name: Create release
        run: |
          set -eo pipefail
          commit_msg=$(git log -1 --pretty=%B)
          echo "$commit_msg"
          echo NEWLINE
          echo NEWLINE
          semver=`echo "$commit_msg" | head -n -1 | awk '{print $2}'`
          echo "$semver"
          echo NEWLINE
          echo NEWLINE
          echo $commit_msg | tail -n +3 > body.txt
          cat body.txt
          gh release create $semver --title $semver -F body.txt --prerelease
        # TODO: remove prerelease flag after testing            ^^^^^^^^^^^^
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
